### ISSUE TITLE
gunicorn failed to start during building

### ISSUE THREAD

**Issue by sigau** [rdmorganiser/rdmo-docker-compose#28]
Hello,

I'm encountering an issue while attempting to run the RDMO Docker. After copying `docker/baseconf.toml` as `conf.toml`, I try to build the container using the `make` command. However, I end up in an infinite loop with the following message:

```
rdc-rdmo      | Run gunicorn
rdc-rdmo      | gunicorn failed to start, retry in 60s
```

I'm having trouble pinpointing the source of the problem. Any insights or suggestions would be greatly appreciated.

Thank you in advance!
Gautier

**Comment by triole** [comment]
Hi,

it is a bit hard to say anything useful from the distance because I tried to reproduce the problem and failed. Do you have any logs inside the `vol/log` folder? Gunicorn should log there as well. Maybe there are any helpful information.

Have a nice day.

**Comment by sigau** [comment]
Hi ,
Sorry, I thought I had attached the logs. Here they are. 

[gunicorn-error.log](https://github.com/rdmorganiser/rdmo-docker-compose/files/13349378/gunicorn-error.log)

**Comment by sigau** [comment]
Hello,


I'm coming back to you because we've tried again to launch rdmo via the docker compose from a fresh installation. However, we still have this problem where after copying docker/baseconf.toml as conf.toml and running make we get stuck on a loop telling us : 

```
rdc-rdmo      | gunicorn failed to start, retry in 60s
rdc-rdmo      | Run gunicorn
```

and when we look at the vol/log /gunicorn-error.log we have still the same error as before : 

```
[2024-02-08 14:23:17 +0000] [12] [INFO] Starting gunicorn 21.2.0
[2024-02-08 14:23:17 +0000] [12] [INFO] Listening at: http://0.0.0.0:8080 (12)
[2024-02-08 14:23:17 +0000] [12] [INFO] Using worker: sync
[2024-02-08 14:23:17 +0000] [13] [INFO] Booting worker with pid: 13
[2024-02-08 14:23:17 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2024-02-08 14:23:17 +0000] [13] [INFO] Worker exiting (pid: 13)
[2024-02-08 14:23:17 +0000] [12] [ERROR] Worker (pid:13) exited with code 3
[2024-02-08 14:23:17 +0000] [12] [ERROR] Shutting down: Master
[2024-02-08 14:23:17 +0000] [12] [ERROR] Reason: Worker failed to boot.
[2024-02-08 14:24:17 +0000] [15] [INFO] Starting gunicorn 21.2.0
[2024-02-08 14:24:17 +0000] [15] [INFO] Listening at: http://0.0.0.0:8080 (15)
[2024-02-08 14:24:17 +0000] [15] [INFO] Using worker: sync
[2024-02-08 14:24:17 +0000] [16] [INFO] Booting worker with pid: 16
[2024-02-08 14:24:17 +0000] [16] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2024-02-08 14:24:17 +0000] [16] [INFO] Worker exiting (pid: 16)
[2024-02-08 14:24:17 +0000] [15] [ERROR] Worker (pid:16) exited with code 3
[2024-02-08 14:24:17 +0000] [15] [ERROR] Shutting down: Master
[2024-02-08 14:24:17 +0000] [15] [ERROR] Reason: Worker failed to boot.
[2024-02-08 14:25:17 +0000] [18] [INFO] Starting gunicorn 21.2.0
[2024-02-08 14:25:17 +0000] [18] [INFO] Listening at: http://0.0.0.0:8080 (18)
[2024-02-08 14:25:17 +0000] [18] [INFO] Using worker: sync
[2024-02-08 14:25:17 +0000] [19] [INFO] Booting worker with pid: 19
[2024-02-08 14:25:17 +0000] [19] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2024-02-08 14:25:17 +0000] [19] [INFO] Worker exiting (pid: 19)
[2024-02-08 14:25:17 +0000] [18] [ERROR] Worker (pid:19) exited with code 3
[2024-02-08 14:25:17 +0000] [18] [ERROR] Shutting down: Master
[2024-02-08 14:25:17 +0000] [18] [ERROR] Reason: Worker failed to boot.
```

Do you have any idea why the instance has this problem and how to fix it? 

Thanks
Gautier
