### ISSUE TITLE
vol/rdmo-app empty after make 

### ISSUE THREAD

**Issue by sigau** [rdmorganiser/rdmo-docker-compose#30]
Hello
while trying to install and run the docker i realised that after doing a make fromscratch the vol/rdmo-app folder is created but is empty, this file remains ide if you leave in the conf.toml commented RDMO_INSTALL_URL=git+https://github.com/rdmorganiser/rdmo@2.0.2 or if you uncomment this line (i changed the version 1.8.2 by default by the latest version 2.0.2) 
Is this empty folder normal? Should I manually make a git clone of rdmo-app in the vol folder? 

Furthermore, I'm wondering, in the event that this problem is resolved, how is the RDMO instance supposed to work? Is it supposed to start at the end of the make? or do we have to enter the container and launch it manually? 

Thank you in advance
Gautier

**Comment by sigau** [comment]
Hi 
By adding git clone https://github.com/rdmorganiser/rdmo-app ${VOLDIR}/rdmo-app  in prepare.sh this correct this problem of empty vol/rdmo-app but then we got the following problem when trying to connect to localhost:8484 we got an Internal Server Error 

when looking to vol/logs/caddy.log : 
```
{"level":"error","ts":1707730650.7898617,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"172.27.0.1","remote_port":"39090","client_ip":"172.27.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:8484","uri":"/","headers":{"Sec-Fetch-Mode":["navigate"],"Accept-Language":["fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-User":["?1"],"User-Agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Site":["none"],"Upgrade-Insecure-Requests":["1"],"Dnt":["1"],"Sec-Gpc":["1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Connection":["keep-alive"]}},"bytes_read":0,"user_id":"","duration":0.409017769,"size":141,"status":500,"resp_headers":{"Server":["Caddy"],"Content-Type":["text/html"],"Content-Length":["141"]}}
```

and when looking to vol/log/gunicorn-error.log : 
```
[2024-02-12 09:36:17 +0000] [12] [INFO] Starting gunicorn 21.2.0
[2024-02-12 09:36:17 +0000] [12] [INFO] Listening at: http://0.0.0.0:8080 (12)
[2024-02-12 09:36:17 +0000] [12] [INFO] Using worker: sync
[2024-02-12 09:36:17 +0000] [13] [INFO] Booting worker with pid: 13
[2024-02-12 10:37:30 +0100] [13] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 77, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/home/rdmo/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 111, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Should this "SECRET_KEY" correspond to "django_secret_key" in my conf.toml and .env ? or should it be fill somewhere else that I miss ?

**Comment by sigau** [comment]
Hello !
So i finally found the solution : 
we need to put a local.py in /vol/rdmo-app/config/settings/local.py after that the doker compose work well
