### ISSUE TITLE
RDMO Runtime Error

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo-docker-compose#4]
Thanks for providing this docker compose set up. Unfortunately I am experiencing some problems. After cloning the repo and changing port and the allowed host (adding the external IP address of the server) in the variables.local, the following error occured after running `make`:

```
rdc-apache  | [Thu Jul 18 15:06:20.038594 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496] mod_wsgi (pid=8): Failed to exec Python script file '/vol/rdmo-app/config/wsgi.py'.
rdc-apache  | [Thu Jul 18 15:06:20.038692 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496] mod_wsgi (pid=8): Exception occurred processing WSGI script '/vol/rdmo-app/config/wsgi.py'.
rdc-apache  | [Thu Jul 18 15:06:20.038970 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496] Traceback (most recent call last):
rdc-apache  | [Thu Jul 18 15:06:20.039066 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]   File "/vol/rdmo-app/config/wsgi.py", line 7, in <module>
rdc-apache  | [Thu Jul 18 15:06:20.039080 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]     application = get_wsgi_application()
rdc-apache  | [Thu Jul 18 15:06:20.039099 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]   File "/vol/ve/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
rdc-apache  | [Thu Jul 18 15:06:20.039110 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]     django.setup(set_prefix=False)
rdc-apache  | [Thu Jul 18 15:06:20.039127 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]   File "/vol/ve/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
rdc-apache  | [Thu Jul 18 15:06:20.039137 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]     apps.populate(settings.INSTALLED_APPS)
rdc-apache  | [Thu Jul 18 15:06:20.039153 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]   File "/vol/ve/lib/python3.5/site-packages/django/apps/registry.py", line 83, in populate
rdc-apache  | [Thu Jul 18 15:06:20.039163 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496]     raise RuntimeError("populate() isn't reentrant")
rdc-apache  | [Thu Jul 18 15:06:20.039205 2019] [wsgi:error] [pid 8:tid 140556231497472] [remote 127.0.0.1:38496] RuntimeError: populate() isn't reentrant
```

* Host-OS: Debian 9.9
* Docker: 18.09.8

What might be the problem here?

**Comment by zalpany2000** [comment]
same issue here !

**Comment by jochenklar** [comment]
Thanks for reporting. We are currently a bit understaffed, but I will look into it.

**Comment by jochenklar** [comment]
We did some changes to the setup, is the error still there?

**Comment by zalpany2000** [comment]
@jochenklar it was solved, we were able to deploy it, many thanks

**Comment by jochenklar** [comment]
Ok, cool.
